artist:
  name: Melwy
  tagline: Data against diseases
  # seo_title:
  # seo_description:
  # contact_twitter_username:
  # contact_phone: 
  # contact_email: 

social:
  - name: school
    url: https://melwy.com/blog
  - name: feather
    url: https://instagram.com
  - name: Twitter
    url: https://twitter.com
  - name: Youtube
    url: https://youtube.com
  - name: slack
    url: https://spotify.com

site_language: en
